name: Deploy to Azure Function

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azcli@v1

    - name: Deploy to Azure Function
      run: |
        az functionapp deployment source config update \
        --resource-group MadSharkABI_ODG \
        --name ODGAPI \
        --repo-url https://github.com/Metsey1982/ODGAPI_AF.git \
        --branch master \
        --access-key ${{ secrets.AZURE_FUNCTION_APP_ACCESS_KEY }}
